In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
pd.options.mode.chained_assignment = None 

In [3]:
df = pd.read_csv("Books.csv")

In [4]:
def combined_features(row):
    return str(row["title"])+" "+str(row["authors"])+" "+str(row["publisher"])
df["combined_features"] = df.apply(combined_features, axis =1)

In [5]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
cs = cosine_similarity(count_matrix)

In [23]:
book_user_likes = "Harry Potter and the Chamber of Secrets (Harry Potter  #2)"
def get_id(title):
    return df[df.title == title]["bookID"].values[0]
book_ID = get_id(book_user_likes)

In [24]:
similar_books = list(enumerate(cs[book_ID]))
del similar_books[0]

In [25]:
sorted_similar_books = sorted(similar_books, key=lambda x:x[1], reverse=True)

In [26]:
def get_title(index):
    return df[df.bookID == index]["title"].values[0]
i=0
for book in sorted_similar_books:
    print(get_title(book[0]))
    i+=1
    if i>15:
        break

Harry Potter and the Chamber of Secrets (Harry Potter  #2)
Harry Potter and the Half-Blood Prince (Harry Potter  #6)
Truth and Fiction in The Da Vinci Code: A Historian Reveals What We Really Know about Jesus  Mary Magdalene & Constantine
Harrius Potter et Philosophi Lapis
Harry Potter and the Order of the Phoenix (Harry Potter  #5)
Harry Potter and the Prisoner of Azkaban (Harry Potter  #3)
Harry Potter and the Philosopher's Stone (Harry Potter  #1)
Unauthorized Harry Potter Book Seven News: "Half-Blood Prince" Analysis and Speculation
Dr. Jekyll and Mr. Hyde (Bullseye Chillers)
J.K. Rowling's Harry Potter Novels: A Reader's Guide
Dornen des Glücks (Das Erbe von Foxworth Hall  #3)
Open City 6: The Only Woman He Ever Left
Harry Potter y el misterio del príncipe (Harry Potter  #6)
Das Zauberer-Handbuch - Die Magische Welt der Joanne K. Rowling von A bis Z
Harry Potter ve Sırlar Odası (Harry Potter  #2)
Mugglenet.Com's What Will Happen in Harry Potter 7: Who Lives  Who Dies  Who Falls in